[features]
seeds = false
skip-lint = false
[programs.localnet]
solana = "BHz6MJGvo8PJaBFqaxyzgJYdY6o8h1rBgsRrUmnHCU9k"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "keypairs/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
